image: amazoncorretto:latest

stages:
  - build

before_script:
  - chmod +x mvnw

build:
  stage: build
  script: ./mvnw package
  artifacts:
    paths:
      - target/spring-cloud-config-s3-0.0.1-SNAPSHOT.jar
